package sansanvn.web.chatweb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sansanvn.web.chatweb.entity.DBChatMessage;
import sansanvn.web.chatweb.entity.DBChatMessageExample;

public interface DBChatMessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	long countByExample(DBChatMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int deleteByExample(DBChatMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int insert(DBChatMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int insertSelective(DBChatMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	List<DBChatMessage> selectByExample(DBChatMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	DBChatMessage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") DBChatMessage record, @Param("example") DBChatMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByExample(@Param("record") DBChatMessage record, @Param("example") DBChatMessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByPrimaryKeySelective(DBChatMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.dbchat_message
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByPrimaryKey(DBChatMessage record);
}