package sansanvn.web.chatweb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sansanvn.web.chatweb.entity.DBUser;
import sansanvn.web.chatweb.entity.DBUserExample;

public interface DBUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	long countByExample(DBUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int deleteByExample(DBUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int insert(DBUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int insertSelective(DBUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	List<DBUser> selectByExample(DBUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	DBUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") DBUser record, @Param("example") DBUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByExample(@Param("record") DBUser record, @Param("example") DBUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByPrimaryKeySelective(DBUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	int updateByPrimaryKey(DBUser record);
}