package sansanvn.web.chatweb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sansanvn.web.chatweb.entity.DBUserInRoom;
import sansanvn.web.chatweb.entity.DBUserInRoomExample;

public interface DBUserInRoomMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	long countByExample(DBUserInRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int deleteByExample(DBUserInRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int insert(DBUserInRoom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int insertSelective(DBUserInRoom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	List<DBUserInRoom> selectByExample(DBUserInRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	DBUserInRoom selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") DBUserInRoom record, @Param("example") DBUserInRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int updateByExample(@Param("record") DBUserInRoom record, @Param("example") DBUserInRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int updateByPrimaryKeySelective(DBUserInRoom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.db_user_in_room
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	int updateByPrimaryKey(DBUserInRoom record);
}