package sansanvn.web.chatweb.entity;

public class DBChatRoom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.dbchatroom.id
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.dbchatroom.roomname
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	private String roomname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.dbchatroom.id
	 * @return  the value of public.dbchatroom.id
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.dbchatroom.id
	 * @param id  the value for public.dbchatroom.id
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.dbchatroom.roomname
	 * @return  the value of public.dbchatroom.roomname
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public String getRoomname() {
		return roomname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.dbchatroom.roomname
	 * @param roomname  the value for public.dbchatroom.roomname
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}
}