package sansanvn.web.chatweb.entity;

public class DBUserInRoom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db_user_in_room.id
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db_user_in_room.idroom
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	private Integer idroom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db_user_in_room.username
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db_user_in_room.id
	 * @return  the value of public.db_user_in_room.id
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db_user_in_room.id
	 * @param id  the value for public.db_user_in_room.id
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db_user_in_room.idroom
	 * @return  the value of public.db_user_in_room.idroom
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	public Integer getIdroom() {
		return idroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db_user_in_room.idroom
	 * @param idroom  the value for public.db_user_in_room.idroom
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	public void setIdroom(Integer idroom) {
		this.idroom = idroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db_user_in_room.username
	 * @return  the value of public.db_user_in_room.username
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db_user_in_room.username
	 * @param username  the value for public.db_user_in_room.username
	 * @mbg.generated  Thu Aug 01 01:07:55 ICT 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}