package sansanvn.web.chatweb.entity;

public class DBUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db_user.id
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db_user.username
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.db_user.pwd_raw
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	private String pwdRaw;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db_user.id
	 * @return  the value of public.db_user.id
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db_user.id
	 * @param id  the value for public.db_user.id
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db_user.username
	 * @return  the value of public.db_user.username
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db_user.username
	 * @param username  the value for public.db_user.username
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.db_user.pwd_raw
	 * @return  the value of public.db_user.pwd_raw
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public String getPwdRaw() {
		return pwdRaw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.db_user.pwd_raw
	 * @param pwdRaw  the value for public.db_user.pwd_raw
	 * @mbg.generated  Mon Jul 22 22:55:34 ICT 2019
	 */
	public void setPwdRaw(String pwdRaw) {
		this.pwdRaw = pwdRaw;
	}
}